name: Concourse build image

on:
  workflow_dispatch: {}
  push:
    paths:
      - rpi/ci/

jobs:
  build-and-deploy-concourse-build:
    runs-on: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2
      - name: Log in to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push"
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./rpi/ci
          file: ./rpi/ci/build.Dockerfile
          tags: ghcr.io/joern19/concourse-build:${{ github.run_number }}
